name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform fmt/plan
        run: |
          terraform -chdir=terraform fmt -check
          terraform -chdir=terraform init -backend=false
          terraform -chdir=terraform plan -lock=false
      - name: Helm lint
        run: helm lint helm/ray-serve