apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ray-serve
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ray-serve
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: queue_depth
        target:
          type: AverageValue
          averageValue: "{{ .Values.autoscaling.queueDepthTarget }}"